// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzidwonypxpbuyetiaun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aWR3b255cHhwYnV5ZXRpYXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTc0NzIsImV4cCI6MjA2NTEzMzQ3Mn0.vLt-JS5cRrtVvQRZoPw6u2jMz92Q_jmhtcaDa9Gsycg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);